#!/usr/bin/env node
/**
 * Reads the compiled DiceBattle artifact from Foundry and writes a typed
 * TS file at apps/web/lib/abi.ts so the frontend can import the ABI without
 * duplication or manual copy-paste.
 *
 * Usage:
 *   pnpm sync-abi
 *
 * Runs automatically after every deploy (see root package.json scripts).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const artifactPath = join(
  root,
  "packages",
  "contracts",
  "out",
  "DiceBattle.sol",
  "DiceBattle.json"
);

const outPath = join(root, "apps", "web", "lib", "abi.ts");

function main() {
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  } catch (err) {
    console.error(
      `\n❌ Could not read Foundry artifact at:\n   ${artifactPath}\n\n` +
        `Did you run 'forge build' in packages/contracts first?\n`
    );
    process.exit(1);
  }

  if (!artifact.abi || !Array.isArray(artifact.abi)) {
    console.error("❌ Artifact has no 'abi' array. Is it a valid Foundry build output?");
    process.exit(1);
  }

  const content = `/**
 * ABI of the DiceBattle contract.
 *
 * AUTO-GENERATED by scripts/sync-abi.mjs — do NOT edit by hand.
 * Source: packages/contracts/out/DiceBattle.sol/DiceBattle.json
 *
 * To regenerate:
 *   cd packages/contracts && forge build
 *   cd ../.. && pnpm sync-abi
 */
export const DICE_BATTLE_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, content, "utf8");

  console.log(`✅ Synced ${artifact.abi.length} ABI entries to ${outPath.replace(root + "/", "")}`);
}

main();
